//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkeletonExp.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_AUTHOR_NAME                 6
#define IDS_COPYRIGHT                   7
#define IDS_DESC_LONG                   8
#define IDS_DESC_SHORT                  9
#define IDS_MESSAGE1                    10
#define IDS_MESSAGE2                    11
#define IDS_FILE_EXT                    12
#define IDB_BITMAP1                     104
#define IDB_BITMAP2                     105
#define IDD_PANEL_FORMAT                106
#define IDB_BITMAP3                     106
#define IDD_PANEL_MESH                  106
#define IDD_PANEL1                      108
#define IDD_PANEL                       108
#define IDD_PANEL_BIND                  112
#define IDD_PANEL_SKELETON              112
#define IDD_PANEL_ANIM                  113
#define IDD_PANEL_ANIMATION             113
#define IDD_PANEL_BSP                   114
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_BINARYCOMPRESSED            1003
#define IDC_OK                          1004
#define IDC_CANCEL                      1005
#define IDC_EDIT1                       1006
#define IDC_PREVIEW                     1006
#define IDC_EDIT_THRESHOLD_POSITION     1006
#define IDC_EDIT_LEVELSCALE             1006
#define IDC_BUTTON_RESET                1006
#define IDC_RADIO1                      1007
#define IDC_RADIO_STEP                  1007
#define IDC_EDIT2                       1007
#define IDC_EDIT_MAXERROR               1007
#define IDC_RADIO_LINEAR                1008
#define IDC_RADIO_SPLINE                1009
#define IDC_EDIT_THRESHOLD_ROTATION     1010
#define IDC_EDIT3                       1011
#define IDC_EDIT_THRESHOLD_SCALE        1011
#define IDC_OTHER                       1017
#define IDC_EXPORT_ALL                  1023
#define IDC_BUTTON_OPTION               1026
#define IDC_ROLLUP_WND                  1028
#define IDC_STATIC_RECT                 1029
#define IDC_EXPORT_BINDINFO             1040
#define IDC_NODE_LIST                   1041
#define IDC_RADIO_FOUTH                 1042
#define IDC_RADIO_SECOND                1043
#define IDC_RADIO_NORMAL                1044
#define IDC_RADIO_DOUBLE                1045
#define IDC_RADIO_FOURFOLD              1046
#define IDC_MESH_SORT                   1047
#define IDC_EXPORT_DUMMY                1048
#define IDC_CHECK_POSITION              1048
#define IDC_VERTEX_COLOR                1049
#define IDC_CHECK_NORMAL                1049
#define IDC_EXPORT_QUAT                 1050
#define IDC_EXPORT_MAX_FRAMETIME        1051
#define IDC_EXPORT_FRMAESORT_MODE       1052
#define IDC_EXPORT_FRMAESORT_MODE2      1053
#define IDC_EXPORT_SPLIT_MESH           1053
#define IDC_TANGENT_BINORMAL            1054
#define IDC_CHECK_TANGENT               1054
#define IDC_ALL_TEXCOORD                1055
#define IDC_CHECK_TEXCOORD              1055
#define IDC_EXPORT_MATRIX               1056
#define IDC_CHECK_TEXCOORD2             1056
#define IDC_1_COLOR2                    1057
#define IDC_MESH_SORT2                  1057
#define IDC_STATIC_MESH                 1057
#define IDC_CHECK_COLOR                 1057
#define IDC_2_COLOR3                    1058
#define IDC_CHECK_LOD                   1058
#define IDC_3_COLOR4                    1059
#define IDC_CHECK_LOD2                  1059
#define IDC_CHECK_COMPRESS              1059
#define IDC_CHECK_COMPRESS_POS          1059
#define IDC_4_COLOR5                    1060
#define IDC_CHECK_COMPRESS2             1060
#define IDC_CHECK_PROPERTY              1060
#define IDC_5_COLOR6                    1061
#define IDC_CHECK_COMPRESS_NORMAL       1061
#define IDC_6_COLOR7                    1062
#define IDC_CHECK_COMPRESS_TEXCOORD     1062
#define IDC_7_COLOR8                    1063
#define IDC_                            1063
#define IDC_TRANSFORM_MESH              1063
#define IDC_VERTEX_COLOR9               1064
#define IDC_8_COLOR9                    1064
#define IDC_CHECK_SWAP_YZ               1064
#define IDC_CHECK_COMPRESS_WEIGHT       1064
#define IDC_CHECK_SKELETON              1065
#define IDC_CHECK_ANIMATION             1066
#define IDC_CHECK_MESH                  1067
#define IDC_RADIO_SKELETAL              1068
#define IDC_RADIO_RIGID                 1069
#define IDC_TREE_BONE                   1070
#define IDC_RADIO_BSP                   1070
#define IDC_RADIO_ALLFRAME              1071
#define IDC_CHECK_MODEL                 1071
#define IDC_RADIO_KEYFRAME              1072
#define IDC_CHECK_ANIMATION2            1072
#define IDC_CHECK_PART                  1072
#define IDC_TREE_ANIMATION              1073
#define IDC_TREE_MESH                   1075
#define IDC_TREE_BSP                    1078
#define IDC_CHECK1                      1079
#define IDC_CHECK_MERGE                 1079
#define IDC_CHECK_COMPRESS_QUATERNION   1079
#define IDC_STATIC_LODSCALE             1080
#define IDC_STATIC_MAXERROR             1081
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
